name: Generate SHOWTURK M3U8

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Run ShowTurk script
        run: |
          python3 code/showturk.py

      - name: Commit & push if file changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f source/showturk.m3u8 ]; then
            git add source/showturk.m3u8

            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update ShowTurk stream"
              git push
            fi
          else
            echo "No stream file generated"
            exit 1
          fi
